//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session2Entities : DbContext
    {
        public Session2Entities()
            : base("name=Session2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookLoans> BookLoans { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BookTransfers> BookTransfers { get; set; }
        public virtual DbSet<ReaderRegistrations> ReaderRegistrations { get; set; }
        public virtual DbSet<Readers> Readers { get; set; }
        public virtual DbSet<ReadingRooms> ReadingRooms { get; set; }
    }
}
